# Generated by Django 3.0.4 on 2020-03-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0002_auto_20200318_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_store',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
