# Generated by Django 3.0.3 on 2020-03-20 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0005_auto_20200318_1905'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book_store',
            table='Book_store',
        ),
    ]
