# Generated by Django 3.0.3 on 2020-03-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0006_auto_20200320_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='book',
            table='Book',
        ),
        migrations.AlterModelTable(
            name='book_available',
            table='Book_available',
        ),
        migrations.AlterModelTable(
            name='book_ordered',
            table='Book_ordered',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='Cart',
        ),
        migrations.AlterModelTable(
            name='complaint_record',
            table='Complaint_record',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
        migrations.AlterModelTable(
            name='customer_address',
            table='Customer_address',
        ),
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
        migrations.AlterModelTable(
            name='review',
            table='Review',
        ),
        migrations.AlterModelTable(
            name='to_read_list',
            table='To_read_list',
        ),
        migrations.AlterModelTable(
            name='user_list',
            table='user_list',
        ),
    ]
