# Generated by Django 3.0.3 on 2020-03-20 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0007_auto_20200320_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='store_id',
            field=models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, to='newApp.Book_store'),
        ),
    ]
