# Generated by Django 3.0.3 on 2020-03-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0008_auto_20200320_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_address',
            name='address_no',
            field=models.IntegerField(unique=True),
        ),
    ]
