# Generated by Django 3.0.3 on 2020-03-23 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0011_order_address_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='store_id',
            new_name='store_id_fk',
        ),
    ]
