# Generated by Django 3.0.3 on 2020-03-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0012_auto_20200323_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='store_id_fk',
            new_name='store_id',
        ),
    ]
