# Generated by Django 3.0.3 on 2020-03-23 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0013_auto_20200323_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_ordered',
            old_name='order_id',
            new_name='order_id_fk',
        ),
    ]
