# Generated by Django 3.0.3 on 2020-03-24 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0014_auto_20200323_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_ordered',
            old_name='order_id_fk',
            new_name='order_id',
        ),
    ]
