# Generated by Django 3.0.3 on 2020-03-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0015_auto_20200324_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_date',
            field=models.DateTimeField(null=True),
        ),
    ]
