# Generated by Django 3.0.3 on 2020-03-24 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0016_order_cancelled_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliverd_date',
            new_name='delivered_date',
        ),
    ]
