# Generated by Django 3.0.3 on 2020-03-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0017_auto_20200324_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_of_order',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
