# Generated by Django 3.0.3 on 2020-03-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0018_auto_20200324_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancelled_date',
            field=models.DateField(null=True),
        ),
    ]
