# Generated by Django 3.0.3 on 2020-03-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0020_auto_20200324_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='no_of_copies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
