# Generated by Django 3.0.3 on 2020-03-24 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0021_auto_20200324_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_list',
            name='store_id',
        ),
        migrations.AddField(
            model_name='user_list',
            name='store_email',
            field=models.ForeignKey(db_column='store_email', null=True, on_delete=django.db.models.deletion.CASCADE, to='newApp.Book_store', to_field='email'),
        ),
    ]
