# Generated by Django 3.0.4 on 2020-03-18 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=20)),
                ('year_of_publish', models.IntegerField()),
                ('price', models.IntegerField()),
                ('copies_sold', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book_store',
            fields=[
                ('store_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=10)),
                ('rating', models.IntegerField()),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_list',
            fields=[
                ('user_list_entry', models.AutoField(primary_key=True, serialize=False)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Book_store')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='To_read_list',
            fields=[
                ('read_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('description', models.CharField(max_length=200)),
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('D', 'Delivered'), ('P', 'Processing'), ('C', 'Cancelled')], max_length=1)),
                ('date_of_order', models.DateTimeField(auto_now=True)),
                ('expected_delivery_date', models.DateField(null=True)),
                ('deliverd_date', models.DateField(null=True)),
                ('total_price', models.FloatField()),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Book_store')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_no', models.IntegerField()),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=6)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint_record',
            fields=[
                ('complain_no', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_entry', models.DateField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Book_ordered',
            fields=[
                ('Book_ordered_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Book')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Book_available',
            fields=[
                ('no_of_copies', models.IntegerField()),
                ('book_available_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Customer')),
            ],
        ),
    ]
