# Generated by Django 3.0.4 on 2020-03-29 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=20)),
                ('year_of_publish', models.IntegerField()),
                ('copies_sold', models.IntegerField()),
                ('rating', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Book',
            },
        ),
        migrations.CreateModel(
            name='Book_store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=10)),
                ('rating', models.IntegerField()),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'Book_store',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='user_list',
            fields=[
                ('user_list_entry', models.AutoField(primary_key=True, serialize=False)),
                ('store_email', models.ForeignKey(db_column='store_email', null=True, on_delete=django.db.models.deletion.CASCADE, to='newApp.Book_store', to_field='email')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Customer')),
            ],
            options={
                'db_table': 'user_list',
            },
        ),
        migrations.CreateModel(
            name='To_read_list',
            fields=[
                ('read_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Customer')),
            ],
            options={
                'db_table': 'To_read_list',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('rating', models.FloatField(default=0.0)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Customer')),
            ],
            options={
                'db_table': 'Review',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Delivered', 'Delivered'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('date_of_order', models.DateTimeField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('cancelled_date', models.DateField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, max_length=20, null=True)),
                ('cancellation_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('total_price', models.FloatField()),
                ('address_no', models.IntegerField(default=0)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Book_store')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Customer')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Customer_address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_no', models.IntegerField()),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=6)),
                ('is_current', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Customer')),
            ],
            options={
                'db_table': 'Customer_address',
            },
        ),
        migrations.CreateModel(
            name='Complaint_record',
            fields=[
                ('complain_no', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Order')),
            ],
            options={
                'db_table': 'Complaint_record',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_entry', models.DateField(auto_now_add=True)),
                ('no_of_copies', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Book')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Book_store')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Customer')),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Book_ordered',
            fields=[
                ('Book_ordered_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_copies', models.IntegerField(default=0)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Book')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Order')),
            ],
            options={
                'db_table': 'Book_ordered',
            },
        ),
        migrations.CreateModel(
            name='Book_available',
            fields=[
                ('no_of_copies', models.IntegerField(default=0)),
                ('book_available_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.Book')),
                ('store_email', models.ForeignKey(db_column='store_email', on_delete=django.db.models.deletion.CASCADE, to='newApp.Book_store', to_field='email')),
            ],
            options={
                'db_table': 'Book_available',
            },
        ),
    ]
