# Generated by Django 3.0.4 on 2020-03-18 19:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0003_auto_20200318_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_available',
            name='user_id',
        ),
        migrations.AddField(
            model_name='book_available',
            name='store_email',
            field=models.ForeignKey(db_column='store_email', default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='newApp.Book_store', to_field='email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
